light_threads = 100
heavy_threads = 20
source = "/fish/syncthing/Music Archive"
target = "/fish/syncthing/Music"

[copier]
inputs = [".jpg", ".jpeg", ".png", ".opus"]

[converter]
inputs = [".wav", ".pcm", ".flac", ".mp3"]
output = ".ogg"
exe = "~/freac-1.1.6-linux-x86_64.AppImage"
cmd = "-e opus -b {bitrate} {input} -o {output}"
config_update = "media-archon-override.toml"

[converter.cmd_args]
bitrate = 160
