# walkers = 100
# converters = 20
tgt_dir = "/fish/syncthing/Music"

[copier]
inputs = [".jpg", ".jpeg", ".png", ".opus"]

[converter]
inputs = [".wav", ".pcm", ".flac", ".mp3"]
output = ".ogg"
exe = "~/freac-continuous-linux-x86_64.AppImage"
cmd = "freaccmd --quiet -e opus --bitrate {bitrate} {input} -o {output}"
config = "media-archon-override.toml"

[converter.cmd_args]
bitrate = 160
