# walkers = 100
# converters = 20
source = "/fish/syncthing/Music Archive"
target = "/fish/syncthing/Music"

[copier]
inputs = [".jpg", ".jpeg", ".png", ".opus"]

[converter]
inputs = [".wav", ".pcm", ".flac", ".mp3"]
output = ".ogg"
exe = "~/freac-1.1.6-linux-x86_64.AppImage"
cmd = "-e opus -b 160 {input} -o {output}"
config = "media-archon-override.toml"
